import { describe, it, expect } from 'bun:test';
import {
  parseInterviewFindings,
  InterviewFindingsValidationError,
  validateInterviewFindings,
  validateEvidenceStrategy,
  synthesizeProjectEntry,
  synthesizeLearnings,
  synthesizeClaudeLocal,
  type DetectedRepoForSynthesis,
} from '../interview/findings.js';
import type { InterviewFindings } from '../types.js';

function makeFindings(overrides: Partial<InterviewFindings> = {}): InterviewFindings {
  return {
    evidenceStrategy: 'test-output',
    evidenceRationale: 'SDK repo — verifier reads test runner output for proof.',
    verificationNotes: 'Set WORKOS_API_KEY and WORKOS_CLIENT_ID env vars before running tests.',
    description: 'AuthKit SDK for Next.js apps',
    commandOverrides: { test: 'pnpm test:unit' },
    learnings: [
      { topic: 'Architecture', content: 'Cookie-based session encrypted with iron-session.' },
      { topic: 'Testing', content: 'Mocks live in `src/__mocks__/`; never call the real WorkOS API.' },
    ],
    conventions: [{ rule: 'Always run typecheck before commit', reason: 'CI rejects type errors.' }],
    repoType: 'sdk',
    hasExampleApp: false,
    testFramework: 'vitest',
    ciProvider: 'github-actions',
    ...overrides,
  };
}

function makeDetected(overrides: Partial<DetectedRepoForSynthesis> = {}): DetectedRepoForSynthesis {
  return {
    name: 'authkit-nextjs',
    path: './authkit-nextjs',
    remote: 'git@github.com:workos/authkit-nextjs.git',
    language: 'typescript',
    packageManager: 'pnpm',
    description: 'autogenerated from package.json',
    commands: {
      setup: 'pnpm install',
      test: 'pnpm test',
      build: 'pnpm build',
      lint: 'pnpm lint',
    },
    evidenceStrategy: 'ui-screenshot', // intentionally wrong — interview overrides
    ...overrides,
  };
}

describe('validateInterviewFindings', () => {
  it('accepts a well-formed payload', () => {
    const findings = makeFindings();
    expect(validateInterviewFindings(findings)).toEqual(findings);
  });

  it('accepts optional credentials when present', () => {
    const findings = makeFindings({ credentials: '~/.config/case/credentials' });
    const out = validateInterviewFindings(findings);
    expect(out.credentials).toBe('~/.config/case/credentials');
  });

  it('rejects null or array top-level values', () => {
    expect(() => validateInterviewFindings(null)).toThrow(InterviewFindingsValidationError);
    expect(() => validateInterviewFindings([])).toThrow(InterviewFindingsValidationError);
    expect(() => validateInterviewFindings('hi')).toThrow(InterviewFindingsValidationError);
  });

  it('rejects missing required fields', () => {
    const partial = { ...makeFindings(), evidenceStrategy: undefined } as unknown;
    expect(() => validateInterviewFindings(partial)).toThrow(/evidenceStrategy/);
  });

  it('rejects an invalid evidenceStrategy enum value', () => {
    const bad = { ...makeFindings(), evidenceStrategy: 'totally-made-up' };
    expect(() => validateInterviewFindings(bad)).toThrow(/evidenceStrategy/);
  });

  it('rejects an invalid repoType enum value', () => {
    const bad = { ...makeFindings(), repoType: 'plugin' };
    expect(() => validateInterviewFindings(bad)).toThrow(/repoType/);
  });

  it('rejects non-boolean hasExampleApp', () => {
    const bad = { ...makeFindings(), hasExampleApp: 'yes' };
    expect(() => validateInterviewFindings(bad)).toThrow(/hasExampleApp/);
  });

  it('rejects non-string credentials when present', () => {
    const bad = { ...makeFindings(), credentials: 42 };
    expect(() => validateInterviewFindings(bad)).toThrow(/credentials/);
  });

  it('rejects malformed learnings entries', () => {
    const bad = { ...makeFindings(), learnings: [{ topic: 'x' }] };
    expect(() => validateInterviewFindings(bad)).toThrow(/learnings\[0\]\.content/);
  });

  it('rejects malformed conventions entries', () => {
    const bad = { ...makeFindings(), conventions: [{ rule: 'r' }] };
    expect(() => validateInterviewFindings(bad)).toThrow(/conventions\[0\]\.reason/);
  });

  it('rejects non-string commandOverrides values', () => {
    const bad = { ...makeFindings(), commandOverrides: { test: 123 } };
    expect(() => validateInterviewFindings(bad)).toThrow(/commandOverrides\.test/);
  });

  it('ignores unknown top-level fields', () => {
    const withExtras = { ...makeFindings(), unexpected: 'value', extras: [1, 2] };
    const out = validateInterviewFindings(withExtras);
    expect((out as unknown as Record<string, unknown>).unexpected).toBeUndefined();
  });
});

describe('parseInterviewFindings', () => {
  it('returns null on invalid input (graceful degradation)', () => {
    expect(parseInterviewFindings(null)).toBeNull();
    expect(parseInterviewFindings({ evidenceStrategy: 'oops' })).toBeNull();
  });

  it('returns validated findings on valid input', () => {
    const findings = makeFindings();
    expect(parseInterviewFindings(findings)).toEqual(findings);
  });
});

describe('validateEvidenceStrategy', () => {
  it('passes cleanly for test-output on an sdk', () => {
    const result = validateEvidenceStrategy(makeFindings({ repoType: 'sdk', evidenceStrategy: 'test-output' }));
    expect(result.ok).toBe(true);
    expect(result.warnings).toEqual([]);
  });

  it('passes cleanly for ui-screenshot on an app', () => {
    const result = validateEvidenceStrategy(
      makeFindings({ repoType: 'app', evidenceStrategy: 'ui-screenshot', hasExampleApp: true }),
    );
    expect(result.ok).toBe(true);
    expect(result.warnings).toEqual([]);
  });

  it('warns when ui-screenshot is chosen for an sdk', () => {
    const result = validateEvidenceStrategy(
      makeFindings({ repoType: 'sdk', evidenceStrategy: 'ui-screenshot', hasExampleApp: false }),
    );
    expect(result.ok).toBe(true);
    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.warnings.some((w) => w.includes('sdk'))).toBe(true);
  });

  it('warns when ui-screenshot is chosen for a library', () => {
    const result = validateEvidenceStrategy(makeFindings({ repoType: 'library', evidenceStrategy: 'ui-screenshot' }));
    expect(result.warnings.some((w) => w.toLowerCase().includes('library'))).toBe(true);
  });

  it('warns when ui-screenshot is chosen for a cli', () => {
    const result = validateEvidenceStrategy(makeFindings({ repoType: 'cli', evidenceStrategy: 'ui-screenshot' }));
    expect(result.warnings.some((w) => w.toLowerCase().includes('cli'))).toBe(true);
  });

  it('warns when ui-screenshot is chosen and there is no example app', () => {
    const result = validateEvidenceStrategy(
      makeFindings({ repoType: 'sdk', evidenceStrategy: 'ui-screenshot', hasExampleApp: false }),
    );
    expect(result.warnings.some((w) => w.includes('example app'))).toBe(true);
  });
});

describe('synthesizeProjectEntry', () => {
  it('lets interview findings override the mechanically-detected evidence strategy', () => {
    const findings = makeFindings({ evidenceStrategy: 'test-output' });
    const detected = makeDetected({ evidenceStrategy: 'ui-screenshot' });
    const entry = synthesizeProjectEntry(findings, detected);
    expect(entry.evidenceStrategy).toBe('test-output');
  });

  it('applies commandOverrides on top of detected commands', () => {
    const findings = makeFindings({ commandOverrides: { test: 'pnpm test:fast' } });
    const detected = makeDetected();
    const entry = synthesizeProjectEntry(findings, detected);
    expect(entry.commands.test).toBe('pnpm test:fast');
    // unmentioned keys preserved
    expect(entry.commands.build).toBe('pnpm build');
    expect(entry.commands.setup).toBe('pnpm install');
  });

  it('keeps detected command when override value is empty', () => {
    const findings = makeFindings({ commandOverrides: { test: '   ' } });
    const detected = makeDetected();
    const entry = synthesizeProjectEntry(findings, detected);
    expect(entry.commands.test).toBe('pnpm test');
  });

  it('adds new commands from overrides not present in detection', () => {
    const findings = makeFindings({ commandOverrides: { verify: 'pnpm verify' } });
    const detected = makeDetected();
    const entry = synthesizeProjectEntry(findings, detected);
    expect(entry.commands.verify).toBe('pnpm verify');
  });

  it('populates verificationNotes on the entry', () => {
    const findings = makeFindings({ verificationNotes: 'auth must be live' });
    const entry = synthesizeProjectEntry(findings, makeDetected());
    expect(entry.verificationNotes).toBe('auth must be live');
  });

  it('populates credentials when provided', () => {
    const findings = makeFindings({ credentials: '~/.config/case/creds' });
    const entry = synthesizeProjectEntry(findings, makeDetected());
    expect(entry.credentials).toBe('~/.config/case/creds');
  });

  it('omits credentials when blank', () => {
    const findings = makeFindings({ credentials: '   ' });
    const entry = synthesizeProjectEntry(findings, makeDetected());
    expect(entry.credentials).toBeUndefined();
  });

  it('uses interview description when present, otherwise falls back to detected', () => {
    const detected = makeDetected({ description: 'from package.json' });
    const interview = makeFindings({ description: 'curated by human' });
    expect(synthesizeProjectEntry(interview, detected).description).toBe('curated by human');

    const interviewBlank = makeFindings({ description: '' });
    expect(synthesizeProjectEntry(interviewBlank, detected).description).toBe('from package.json');
  });

  it('preserves name, path, remote, language, packageManager from detection', () => {
    const findings = makeFindings();
    const detected = makeDetected();
    const entry = synthesizeProjectEntry(findings, detected);
    expect(entry.name).toBe(detected.name);
    expect(entry.path).toBe(detected.path);
    expect(entry.remote).toBe(detected.remote);
    expect(entry.language).toBe(detected.language);
    expect(entry.packageManager).toBe(detected.packageManager);
  });
});

describe('synthesizeLearnings', () => {
  it('produces an empty string when there are no learnings', () => {
    const findings = makeFindings({ learnings: [] });
    expect(synthesizeLearnings(findings)).toBe('');
  });

  it('renders each learning under a topic heading', () => {
    const findings = makeFindings({
      learnings: [
        { topic: 'Auth Flow', content: 'PKCE all the way down.' },
        { topic: 'Sessions', content: 'Encrypted JWE cookies.' },
      ],
    });
    const out = synthesizeLearnings(findings);
    expect(out).toContain('# Repo Learnings');
    expect(out).toContain('## Auth Flow');
    expect(out).toContain('PKCE all the way down.');
    expect(out).toContain('## Sessions');
    expect(out).toContain('Encrypted JWE cookies.');
  });

  it('ends with a single trailing newline', () => {
    const findings = makeFindings();
    const out = synthesizeLearnings(findings);
    expect(out.endsWith('\n')).toBe(true);
    expect(out.endsWith('\n\n')).toBe(false);
  });
});

describe('synthesizeClaudeLocal', () => {
  it('produces an empty string when there are no conventions', () => {
    const findings = makeFindings({ conventions: [] });
    expect(synthesizeClaudeLocal(findings)).toBe('');
  });

  it('renders each convention as a bullet with rule + reason', () => {
    const findings = makeFindings({
      conventions: [
        { rule: 'Use pnpm', reason: 'Lockfile is committed.' },
        { rule: 'No console.log', reason: 'Lint blocks it.' },
      ],
    });
    const out = synthesizeClaudeLocal(findings);
    expect(out).toContain('# CLAUDE.local.md');
    expect(out).toContain('## Conventions');
    expect(out).toContain('Use pnpm');
    expect(out).toContain('Lockfile is committed.');
    expect(out).toContain('No console.log');
  });

  it('ends with a single trailing newline', () => {
    const findings = makeFindings();
    const out = synthesizeClaudeLocal(findings);
    expect(out.endsWith('\n')).toBe(true);
    expect(out.endsWith('\n\n')).toBe(false);
  });
});
