import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { extname, relative, resolve } from 'node:path';

const ASSET_DIRS = ['agents', 'docs', 'ast-rules'] as const;
const TEXT_EXTENSIONS = new Set(['.md', '.yml', '.yaml']);

export async function generatePackageAssets(root = resolve(import.meta.dir, '..', '..')): Promise<string> {
  const assets = await listPackageAssets(root);
  const outPath = resolve(root, 'src/generated/package-assets.ts');
  await mkdir(resolve(root, 'src/generated'), { recursive: true });
  await writeFile(outPath, renderManifest(assets), 'utf-8');
  return outPath;
}

async function listPackageAssets(root: string): Promise<string[]> {
  const assets: string[] = [];
  for (const dir of ASSET_DIRS) {
    await walk(resolve(root, dir), root, assets);
  }
  return assets.sort();
}

async function walk(dir: string, root: string, assets: string[]): Promise<void> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full, root, assets);
      continue;
    }
    if (!entry.isFile() || !TEXT_EXTENSIONS.has(extname(entry.name))) continue;
    assets.push(relative(root, full).replace(/\\/g, '/'));
  }
}

function renderManifest(assets: string[]): string {
  const imports = assets
    .map((asset, index) => `import asset${index} from ${quote(`../../${asset}`)} with { type: 'text' };`)
    .join('\n');
  const entries = assets.map((asset, index) => `  ${quote(asset)}: asset${index},`).join('\n');

  return [
    '/* eslint-disable */',
    '// Generated by src/dev/generate-package-assets.ts. Do not edit by hand.',
    imports,
    '',
    'export const embeddedPackageAssets: Record<string, string> = {',
    entries,
    '};',
    '',
  ].join('\n');
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

if (import.meta.main) {
  const outPath = await generatePackageAssets();
  process.stdout.write(`Generated ${outPath}\n`);
}
